apptentive/apptentive-react-native

- .gitignore
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/RNApptentiveModuleModule.java
- android/src/main/java/com/facebook/react/bridge/ApptentiveReactApplicationContextWrapper.java
- ios/RNApptentiveModule.m
- js/index.js
- sample/App.js
- sample/ios/sample.xcodeproj/project.pbxproj
- sample/src/components/CustomDataModal.js
UI layout is still incorrect but we can address it later
> Added custom data support

- sample/App.js
- sample/src/components/CustomDataModal.js
Not the best way but works for now
> Fixed layouts

- README.md
Also did some general proofreading and editing.
> Add iOS push instructions

- CHANGELOG.md
- apptentive-react-native.podspec
- package.json
(accidentally merged to master last time)
> Fix missing dependency in podspec

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Fix check for registered status on iOS
> Release 5.1.3

- CHANGELOG.md
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/RNApptentiveModule.java
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- sample/App.js
- Fixed Android build issues
- Improved configuration handling
> Release 5.1.4

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/RNApptentiveModule.java
- android/src/main/res/values/strings.xml
- ios/RNApptentiveModule.m
- js/index.js
- js/platform-specific.android.js
- js/platform-specific.ios.js
- package.json
- sample/ios/Podfile
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.3.2
- Apptentive iOS SDK: 5.2.2
> Release 5.3.1

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- ios/RNApptentiveModule.m
- package.json
- sample/ios/Podfile
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.3.3
- Apptentive iOS SDK: 5.2.3
> Release 5.3.2

- LICENSE
- LICENSE.txt
- ios/RNApptentiveModule.xcodeproj/project.pbxproj
- js/index.d.ts
- js/index.js
- js/platform-specific.android.js
- js/platform-specific.ios.js
- package.json
- Add TypeScript declarations file and add to `package.json`.
- Fix documentation comment for `canShowInteraction`.
- ESLint fixes to platform specific files (missing `;`).
[SEA-690](https://apptentive.atlassian.net/browse/SEA-690)
> Add TypeScript Declarations File

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- ios/RNApptentiveModule.m
- package.json
- Fix missing `ios` and `android` directories
> Release 5.4.3

- package.json
Add `apptentive-react-native.podspec` file to included bundled files.
> Add podspec file to included bundled files in package.json

- js/index.js
- Fix `number` types for device custom data
- Change `else if` blocks to `if` as all types return, per ESLint.
> Fix number types for device custom data

- MANUAL INSTALLATION.md
- README.md
- apptentive-react-native.podspec
- Update docs
- Move manual installation documentation (possibly outdated) out of main README.
> Update documentation for new auto-linking capability

- sample61/App.js
Add check for empty keys when running.
> Add check for empty keys

- android/build.gradle
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/RNApptentiveModule.java
Dependencies moved to AndroidX
> AndroidX migration

- sample61/ios/sample61.xcodeproj/project.pbxproj
- sample61/ios/sample61.xcodeproj/xcshareddata/xcschemes/sample61.xcscheme
- sample61/ios/sample61/Info.plist
- sample61/ios/sample61Tests-Bridging-Header.h
- sample61/ios/sample61Tests/sample61Tests.m
- sample61/ios/sample61UITests/Info.plist
- sample61/ios/sample61UITests/sample61UITests.swift
This added a passing iOS UI test to work with in testing CI.
> Passing iOS UI Test

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Android 11 support.
- Apptentive Android SDK: 5.5.4
- Apptentive iOS SDK: 5.2.14
> Release 5.5.3

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Fixed Android 11 support.
- Apptentive Android SDK: 5.5.4
- Apptentive iOS SDK: 5.2.14
> Release 5.5.4

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- sample/ios/Podfile
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.6.0
- Apptentive iOS SDK: 5.3.1
> Release 5.6.0

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Fixed missing iOS header file.
- Apptentive Android SDK: 5.6.0
- Apptentive iOS SDK: 5.3.1
> Release 5.6.1

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Apptentive Android SDK: 5.6.1
- Apptentive iOS SDK: 5.3.1
> Release 5.6.2

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- Apptentive Android SDK: 5.6.2
- Apptentive iOS SDK: 5.3.1
> Release 5.6.3

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- sample/ios/Podfile
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.6.3
- Apptentive iOS SDK: 5.3.3
> Release 5.6.4

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.6.4
- Apptentive iOS SDK: 5.3.3
> Release 5.6.5

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- package.json
- sample/ios/Podfile
- sample/ios/Podfile.lock
- Apptentive Android SDK: 5.7.0
- Apptentive iOS SDK: 5.3.4
> Release 5.7.0

- .travis.yml
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/RNApptentiveModule.java
- apptentive-react-native.podspec
- ios/RNApptentiveModule.m
- js/index.d.ts
- js/index.js
- sample61/App.js
- sample61/android/build.gradle
- sample61/android/gradle/wrapper/gradle-wrapper.properties
- sample61/ios/Podfile.lock
- sample61/package-lock.json
- sample61/package.json
- sample61/yarn.lock
Implement missing Android and iOS flags
> Missing flags

- CHANGELOG.md
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/ApptentiveModule.kt
- android/src/main/res/values/strings.xml
- example/ios/Podfile.lock
- package.json
- Apptentive Android SDK: 5.8.3
- Apptentive iOS SDK: 6.0.2
- Added missing lifecycle callbacks for the Android platform
> Release 6.0.1

- CHANGELOG.md
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/ApptentiveModule.kt
- android/src/main/res/values/strings.xml
- example/ios/Podfile.lock
- package.json
- Apptentive Android SDK: 5.8.3
- Apptentive iOS SDK: 6.0.3
- Fixed typescript functionality in published package
> Release 6.0.2

- CHANGELOG.md
- android/build.gradle
- android/src/main/res/values/strings.xml
- example/ios/Podfile.lock
- package.json
Apptentive Android SDK: 5.8.4
Apptentive iOS SDK: 6.0.4
> Release 6.0.3

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- apptentive-react-native.podspec
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
- Apptentive Android SDK: 5.8.4
- Apptentive iOS SDK: 6.0.9
> Release 6.0.9

- CHANGELOG.md
- android/src/main/res/values/strings.xml
- example/ios/Podfile.lock
- package.json
- Apptentive Android SDK: 5.8.4
- Apptentive iOS SDK: 6.1.0
> Release 6.1.0

- android/build.gradle
- android/src/main/java/com/apptentive/android/sdk/reactlibrary/ApptentiveModule.kt
- yarn.lock
[PBI-5370]
[PBI-5370]: https://apptentive.atlassian.net/browse/PBI-5370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBI-5370 Better handle error states and update apptentive version

- android/src/main/java/com/apptentive/android/sdk/reactlibrary/ApptentiveModule.kt
- package.json
- yarn.lock
[PBI-5336]
Cleaned up the messageCenterNotificaitonObservable in onDestroy. Should prevent memory leaks (if there are any)
[PBI-5336]: https://apptentive.atlassian.net/browse/PBI-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBI-5336 React Native message observer cleanup

- .github/workflows/complete-release.yml
- .github/workflows/publish.yml
- .github/workflows/update-versions.yml
- .scripts/add_changelog_entry.sh
- .scripts/changes.md
- .scripts/update_android_version.sh
- .scripts/update_distribution_version.sh
- .scripts/update_ios_version.sh
> Add workflows for preparing and releasing PBI-1999

- android/build.gradle
- apptentive-react-native.podspec
[PBI-6389](https://alchemer.atlassian.net/browse/PBI-6389)
[PBI-6389]: https://alchemer.atlassian.net/browse/PBI-6389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PBI-6389 6.7.0 upgrade
